comment_width = 60
wrap_comments = true
empty_item_single_line = false
format_strings = true
hex_literal_case = "Upper"
match_block_trailing_comma = true
max_width = 80
newline_style = "Unix"
reorder_impl_items = true
tab_spaces = 2
unstable_features = true
use_field_init_shorthand = true
use_try_shorthand = true
