require("logan.options")
require "logan.binds"
require "logan.plugins"
require "logan.nvim-tree"
require "logan.cmp"
require "logan.lsp"
require "logan.telescope"
require "logan.treesitter"
require "logan.gitsigns"
require "logan.etc"
require "logan.colorshceme"
--vim.cmd "colorscheme system76"
